title: Hello, All! I'm Zubair
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://zubairashfaque.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Zubair Ashfaque # add your name
author-img: zubair_ash.jpg # add your photo
about-author: I am a Data Scientist & Machine Learning Engineer focusing on Deep Learning. Critic Abigail Adams says, “learning is not attained by chance, it must be sought for with ardor and attended to with diligence.” that’s why I am still learning. # add description
social-twitter: zubairashfaque # add your Twitter handle
social-facebook: mianashfaque # add your Facebook handle
social-github: zubairashfaque # add your Github handle
social-linkedin: zubair-ashfaque-ab100621 # add your Linkedin handle
social-email: mianashfaque@gmail.com # add your Email address

# Disqus
discus-identifier: http://disqus.com/by/zubairashfaque # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
